# Generated by Django 3.0.3 on 2020-03-26 12:16

from django.db import migrations, models




class Migration(migrations.Migration):

    dependencies = [
        ('geoLocate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='addressAllowed',
            field=models.BooleanField(default=True),
        ),

    ]
