# Generated by Django 3.0.3 on 2020-03-26 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoLocate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geoLocate.Category'),
        ),
    ]
