# Generated by Django 3.0.3 on 2020-03-26 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoLocate', '0003_auto_20200326_1227'),
    ]

    operations = [

    ]
