# Generated by Django 3.0.3 on 2020-03-26 13:30

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoLocate', '0003_auto_20200326_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=43262),
        ),
    ]
