# Generated by Django 3.0.3 on 2020-03-26 13:33

from django.db import migrations
import json
from django.contrib.gis.geos import fromstr
from pathlib import Path

DATA_FILENAME = 'data.json'
def load_data(apps, schema_editor):
    Request = apps.get_model('geoLocate', 'Request')
    jsonfile = Path(__file__).parents[2] / DATA_FILENAME

    with open(str(jsonfile)) as datafile:
        objects = json.load(datafile)
        for obj in objects['elements']:
            try:
                objType = obj['type']
                if objType == 'node':
                    tags = obj['tags']
                    name = tags.get('name','no-name')
                    longitude = obj.get('lon', 0)
                    latitude = obj.get('lat', 0)
                    location = fromstr(f'POINT({longitude} {latitude})', srid=4326)
                    Request(requestor=name, location = location, addressAllowed=True).save()
            except KeyError:
                pass

class Migration(migrations.Migration):

    dependencies = [
        ('geoLocate', '0005_auto_20200326_1330'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
