# Generated by Django 3.0.3 on 2020-03-26 13:39

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoLocate', '0006_auto_20200326_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
    ]
